config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pins#index'
  resources :pins
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/elevator.rb
class Elevator < ApplicationRecord
  belongs_to :pin
  validates :from, presence: true
  validates :to, presence: true
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :station
  has_one :elevator, dependent: :destroy
  has_one :restroom, dependent: :destroy
  has_one :slope, dependent: :destroy
  has_one :step, dependent: :destroy

  accepts_nested_attributes_for :elevator, allow_destroy: true
  accepts_nested_attributes_for :restroom, allow_destroy: true
  accepts_nested_attributes_for :slope, allow_destroy: true
  accepts_nested_attributes_for :step, allow_destroy: true

  enum data_type:{
    elevator: 1,
    restroom: 2,
    slope: 3,
    step: 4
  }
end

app/models/restroom.rb
class Restroom < ApplicationRecord
  belongs_to :pin
  validates :is_multipurpose, presence: true
end

app/models/slope.rb
class Slope < ApplicationRecord
  belongs_to :pin
  validates :level, presence: true
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :pins
end

app/models/step.rb
class Step < ApplicationRecord
  belongs_to :pin
  validates :level, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def index
    @pins = Pin.all
    @pin = Pin.new
  end

  def new
    @pin = Pin.new(pin_params)
    case @pin.data_type
    when "elevator" then
      @pin.build_elevator
    when "restroom" then
      @pin.build_restroom
    when "slope" then
      @pin.build_slope
    when "step" then
      @pin.build_step
    else
      flash[:alert] = "種別が入力されていません"
      redirect_to pins_path
    end
  end

  def create
    @pin = Pin.new(pin_params)
    @pin.station_id = 1
    if @pin.save
      redirect_to pins_path
    else
      render new_pin_path
    end
  end

  def edit
    @pin = Pin.find(params[:id])
  end

  def update
    @pin = Pin.find(params[:id])
    @pin.update(pin_params)
    redirect_to pins_path
  end

  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
    redirect_to pins_path
  end

  private
  def pin_params
    params.require(:pin).permit(:data_type, :lat, :lng, :floor,
      elevator_attributes: [:description, :from, :to],
      restroom_attributes: [:description, :is_multipurpose],
      step_attributes: [:description, :level],
      slope_attributes: [:description, :level])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pins/index.html.erb
<h1>一覧＆登録画面</h1>
<section class="flash-alert">
  <%= flash[:alert] %>
</section>
<div class="d-flex">
  <div id="map"></div>
  <div id="form-group">
    <section id="currentPositionBtn">現在地を取得</section>
    <%= form_with(model: @pin, url: new_pin_path, method: :get, local: true) do |f| %>
      <div>
        <%= f.label :lat ,"緯度: "%>
        <%= f.text_field :lat, id: "lat", readonly: true %>
        <%= f.label :lng ,"経度: "%>
        <%= f.text_field :lng, id: "lng", readonly: true %>
      </div>
      <div>
        <%= f.label :floor, "階数: "%>
        <%= f.number_field :floor, in: 1..10, value: 1 %>
      </div>
      <div>
        <%= f.label :data_type, "種類: "%>
        <div class="form-select">
          <%= f.select :data_type, Pin.data_types.keys.to_a, prompt: "選択してください" %> 
        </div>
        <%= f.submit "作成", class:"submit-button" %>
      </div>
    <% end %>
    <div id="pins_data" data="<%= @pins.to_json %>"></div>
  </div>
</div>
<div id="index_table">
  <table>
    <thead>
      <tr>
        <td class="set_button_col"></td>
        <td class="station_col"><strong>駅</strong></td>
        <td class="type_col"><strong>種別</strong></td>
        <td class="latlng_col"><strong>緯度</strong></td>
        <td class="latlng_col"><strong>経度</strong></td>
        <td class="delete_button_col"></td>
      </tr>
    </thead>
    <% @pins.each do |p| %>
    <tr>
      <td class="set_button_col">
        <button class="setButton" lat="<%= p.lat %>"lng="<%= p.lng %>" >地図の中心にセット</button>
      </td>
      <td class="station_col"><%= p.station.name %></td>
      <td class="type_col"><%= p.data_type %></td>
      <td class="latlng_col"><%= p.lat %></td>
      <td class="latlng_col"><%= p.lng %></td>
      <td class="delete_button_col"><%= link_to '削除', pin_path(p), method: :delete, data:{confirm: "本当に削除しますか"} %></td>
    </tr>
    <% end %>
  </table>
</div>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAP_KEY"] %>&callback=initMap"></script>

app/views/pins/new.html.erb
<h1>新規作成画面</h1>
<% if @pin.errors.any? %>
  <ul>
  <% @pin.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>
<%= form_with model: @pin, local: true do |f| %>
  <div>
    <%= f.label :data_type, "種別: " %>
    <%= f.text_field :data_type, value: @pin.data_type, readonly: true %>
  </div>
  <div>
    <%= f.label :floor, "階数: " %>
    <%= f.text_field :floor, value: @pin.floor, readonly: true %>
  </div>
  <div>
    <%= f.label :lat, "緯度: " %>
    <%= f.text_field :lat, value: @pin.lat, readonly: true %>
  </div>
  <div>
    <%= f.label :lat, "経度: " %>
    <%= f.text_field :lng, value: @pin.lng, readonly: true %>
  </div>
  <hr>
  <div>
    <%= f.fields_for :elevator do |g| %>
      <%= g.label :description, "説明: "%>
      <%= g.text_area :description %>
      <div>
        <p>「どこから > どこまで」、となるよう書いてください</p>
        <%= g.label :from, "どこから: "%>
        <%= g.number_field :from,value: 1 %>階
        <%= g.label :to, "どこまで: " %>
        <%= g.number_field :to, value: 1 %>階
      </div>
    <% end %>

    <%= f.fields_for :restroom do |g| %>
      <%= g.label :description, "説明: "%>
      <%= g.text_area :description %>
      <%= g.label :is_multipurpose, "多目的トイレ"%>
      <div class="form-select">
        <%= g.select :is_multipurpose, [["あり",true],["なし",false]]%>
      </div>
    <% end %>

    <%= f.fields_for :step do |g| %>
      <%= g.label :description, "説明: "%>
      <%= g.text_area :description %>
      <%= g.label :level, "レベル: "%>
      <div class="form-select">
        <%= g.select :level, [
          ["一人で乗り越えられるが危険", 1],
          ["介助者がいれば乗り越えられる", 2],
          ["介助者がいても乗り越えるのが難しい", 3]
        ], prompt: "選択してください" %>
      </div>
    <% end %>

    <%= f.fields_for :slope do |g| %>
      <%= g.label :description, "説明: "%>
      <%= g.text_area :description %>
      <%= g.label :level, "レベル: "%>
      <div class="form-select">
        <%= g.select :level, [
          ["一人でも上り下りできる", 1],
          ["介助者がいれば上り下りできる", 2],
          ["介助者がいても上り下りが難しい", 3]
        ], prompt: "選択してください" %>
      </div>
    <% end %>
  </div>
  <div class="d-flex">
    <section class="setButton new_button">
      <%= link_to '戻る', pins_path %>
    </section>
    <%= f.submit '投稿', class:"submit-button new_button" %>
  </div>
<% end %>